# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Research"
  url = "#areas"
  weight = 20

[[main]]
  name = "Project"
  url = "https://panarchic.ch"
  weight = 25

[[main]]
  name = "Book"
  url = "#book"
  weight = 28

[[main]]
  name = "Software"
  url = "#software"
  weight = 30

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 40

[[main]]
  name = "Teaching"
  url = "#teaching"
  weight = 50

[[main]]
  name = "Supervision"
  url = "#supervision"
  weight = 55

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/cv.pdf"
#    weight = 70
